nameOverride: user-service
fullnameOverride: user-service
image:
  repository: 014498640042.dkr.ecr.eu-west-2.amazonaws.com/user-service
  tag: dev-4f2619f

env:
  - name: REPO_BACKEND
    value: memory
  - name: PORT
    value: "8080"
probes:
  liveness:
    path: /users/health
  readiness:
    path: /users/ready
