apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-crud-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YassineKaibi/smartovate-eks-project
    targetRevision: main
    path: helm/microservice
    helm:
      valueFiles:
        - values-crud-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
